<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">
<head>
    <title><spring:message code="employee.form.title" /></title>

    <style>
        input.input {
            margin-left: 20px;
        }
    </style>
</head>
<body>
<div>
<br>
<a href="/form/list"><spring:message code="employee.form.list" /></a>
</div>

<div>
    <h3><spring:message code="employee.form.getById" /></h3>
    <form action="/form/details" method="GET">
        <table>
            <tr>
                <td><spring:message code="employee.form.id" /></td>
                <td><input type="input" name="id" class="input"/></td>
            </tr>
        <tr><td></td><td></td></tr>
            <tr>
                <td><input type="submit" value="Get Details"/></td>
                <td><input type="submit" value="Delete Details" onclick="this.form.action='/form/delete';this.form.method='delete'"/></td>
            </tr>
        </table>
    </form>
</div>

<div>
    <h3><spring:message code="employee.form.details" /></h3>
    <form action="/form/add" method="GET">
        <table>
            <tr>
                <td><spring:message code="employee.form.id"/></td>
                <td><input type="input" name="id" class="input" title="It will be autogenerated for new record."/></td>
            </tr>
        <tr><td><spring:message code="employee.form.name" /></td>
            <td><input type="input" name="name" class="input"/></td>
        </tr>
            <tr>
                <td>
                    <spring:message code="employee.form.address" />
                </td>
                <td>
                    <input type="input" name="address" class="input"/>
                </td>
            </tr>
            <tr>
                <td>
                    <spring:message code="employee.form.contact" />
                </td>
                <td>
                    <input type="input" name="contactNum" class="input"/>
                </td>
            </tr>
            <tr>
                <td>
                    <spring:message code="employee.form.role" />
                </td>
                <td>
                    <input type="input" name="role" class="input"/>
                </td>
            </tr>
            <tr>
                <td>
                    <spring:message code="employee.form.department" />
                </td>
                <td>
                    <input type="input" name="department" class="input"/>
                </td>
            </tr>
            <tr><td></td><td></td></tr>
            <tr>
                <td>
                    <input type="submit" value="<spring:message code="employee.form.getEmployee" />"/>
                </td>
                <td>
                    <input type="submit" value="<spring:message code="employee.form.updateEmployee" />" onclick="this.form.action='/form/update'"/>
                </td>
            </tr>
        </table>
    </form>
</div>
</body>
</html>